name: Build and Publish

on:
 push:
  tags:
    - v*.*.*

jobs:
 build:
   runs-on: ${{ matrix.os }}
   strategy:
     matrix:
       os: [macos-latest]
       platform: [x64, arm64]
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Build
       run: |
         swift build -c release

     - name: Copy binary
       run: |
         cp ./.build/release/wechattweak-cli ./wechattweak-cli-${{ matrix.platform }}

     - name: Release
       uses: softprops/action-gh-release@v1
       with:
          files: wechattweak-cli-${{ matrix.platform }}
          token: ${{ secrets.GITHUB_TOKEN }}